language: cpp
compiler: gcc
sudo: required

matrix:
  include:
  - dist: trusty
  - dist: xenial
  - dist: precise

addons:
  apt:
    packages:
    - wget
    - cmake
    # libappimage deps
    - desktop-file-utils
    - libfuse-dev

before_install:
- sudo apt-get update
- sudo apt-get install -y libglib2.0-dev libgdk-pixbuf2.0-dev

script:
- cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX=/usr
- make -j`nproc`
- cpack -V -G DEB

after_success:
  # Add distribution code name to the end of the file name
- OLD_FILE=$(echo *.deb)
- FILE_NAME=$(basename OLD_FILE)
- NEW_FILE_NAME="${FILE_NAME%.*}-$(lsb_release -c | cut -f 2).deb"
- mv $OLD_FILE $NEW_FILE_NAME


deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: ./*.deb
  skip_cleanup: true
  prerelease: true
  overwrite: true
  on:
    repo: azubieta/appimage-gnome-thumbnailer
    branch: master
    tags: true

notifications:
  email: false
