# determine Git commit ID
execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_COMMIT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# determine linux flavor
execute_process(
    COMMAND lsb_release -cs
    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
    OUTPUT_VARIABLE LINUX_FLAVOR
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

message("GIT_COMMIT: ${GIT_COMMIT}")
set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_RELEASE "git${GIT_COMMIT}")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Alexis Lopez Zubieta")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/azubieta/appimage-gnome-thumbnailer")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_SOURCE_DIR}/README.md")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")


set(CPACK_PACKAGE_DESCRIPTION "AppImage Thumbnailer for Gnome")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "AppImage Thumbnailer for Gnome")

set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_PACKAGE_RELEASE}.${CMAKE_SYSTEM_PROCESSOR}-${LINUX_FLAVOR}")
